---
apiVersion: "v1"
kind: "Namespace"
metadata:
  name: "nundefault"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "front"
  namespace: "nundefault"
  labels:
    app: "front"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "front"
  template:
    metadata:
      labels:
        app: "front"
    spec:
      containers:
      - name: "simplewhalejenkins-1"
        image: {{ .vars.container.frontImage }}
        imagePullPolicy: Always
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "125m"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "front-hpa-xnma"
  namespace: "nundefault"
  labels:
    app: "front"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "front"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
